# Generated by Django 3.0.7 on 2022-04-11 18:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('KCI Registerd', 'KCI Registerd'), ('Guard Dog', 'Guard Dog'), ('India Dog Show Winner', 'India Dog Show Winner'), ('Russian Champion', 'Russian Champion')], max_length=62),
        ),
    ]
