# Generated by Django 3.0.7 on 2022-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20220411_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='Energy_Levels',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='Exercise',
            field=models.CharField(choices=[('Moderate', 'Moderate'), ('Significant', 'Significant'), ('Rigorous', 'Rigorous')], default='Significant', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='Hair_Grooming',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Not Required', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='KCI_Registerd',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='No Information', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='Training',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Average', 'Average'), ('Difficult', 'Difficult')], default='No Information', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='affection_with_family',
            field=models.CharField(choices=[('Independant', 'Independant'), ('Balanced', 'Balanced'), ('Cuddly', 'Cuddly')], default='How much you love your dogs', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='aggresive',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='No Information', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='bread_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='No Information', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Litter', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('UP', 'Uttar Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DH', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry')], max_length=100),
        ),
    ]
