# Generated by Django 3.0.7 on 2022-04-13 21:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20220412_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breader_contact',
            field=phone_field.models.PhoneField(blank=True, default='No Information', help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='dog',
            name='breader_name',
            field=models.CharField(default='No Information', max_length=255),
        ),
    ]
