# Generated by Django 3.0.7 on 2022-04-14 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_remove_dog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
