# Generated by Django 3.0.7 on 2022-04-14 16:41

from django.db import migrations, models
import dogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_dogs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.DateField(blank=True, default=dogs.models.one_month_from_today, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='Dogs_type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Pups', 'Pups')], default='pups', max_length=100),
        ),
    ]
