# Generated by Django 3.0.7 on 2022-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
