# Generated by Django 3.0.7 on 2022-04-09 18:18

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='age',
            field=models.DateField(blank=True, default=pages.models.one_month_from_today, null=True),
        ),
    ]
