# Generated by Django 3.0.7 on 2022-04-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teams_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Farm_bread',
        ),
    ]
