# Generated by Django 3.0.7 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220410_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_bread',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
