# Generated by Django 3.0.7 on 2022-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220410_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_slider', models.ImageField(upload_to='slider/%Y/%m/%d/')),
            ],
        ),
    ]
