# Generated by Django 3.0.7 on 2022-04-10 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_dog_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog_slider',
            name='slider_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
